#!/usr/bin/env bash

set -eEuo pipefail

previous_branch="$1"
current_branch="$2"

if [[ "$(git diff --name-only "$previous_branch" "$current_branch" -- package.json package-lock.json)" != "" ]]; then
  echo "Refreshing npm packages" >&2
  npm ci &> /dev/null
fi
